{% set name = "unidiff" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matiasb/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 31d4999ac734032a883e5656763fe1da29c5755a88a39aa8ac3a267b178dff33

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - unidiff
  source_files:
    - tests
  commands:
    - python -m unittest discover -s tests/

about:
  home: https://github.com/matiasb/python-unidiff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple Python library to parse and interact with unified diff data.

extra:
  recipe-maintainers:
    - tovrstra
