{% set name = "unidiff" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unidiff-{{ version }}.tar.gz
  sha256: 5e5d5cfab2dc98be819b74747ab7d9f5af8695369ec8710b93f9ab0f0ae6a449

build:
  # Due to the use of scripts, this cannot be noarch
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pip
  imports:
    - unidiff
  source_files:
    - tests
  commands:
    - pip check
    - python -m unittest discover -s tests/

about:
  home: https://github.com/matiasb/python-unidiff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Simple Python library to parse and interact with unified diff data.'

extra:
  recipe-maintainers:
    - xhochy
    - tovrstra
