{% set name = "unidiff" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matiasb/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 00bd92c4988a2daba239222e579284da48983f81b929fad4249949d6a5496723

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - unidiff
  source_files:
    - tests
  commands:
    - python -m unittest discover -s tests/

about:
  home: https://github.com/matiasb/python-unidiff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple Python library to parse and interact with unified diff data.

extra:
  recipe-maintainers:
    - tovrstra
